* acm.el

acm.el (or, ~acm-mode~) provides a minor mode to assist in competitive
programming, by saving you from tedious tasks like
+ building the program
+ feeding input
+ getting output
+ measuring running time (todo)
+ comparing your results with correct results (todo)

Yes, these tasks are trivial, but it can be really annoying.

*NOTE:* this is in early development, and your improvements are
welcome.  Since I'm an Emacs Lisp beginner, you are encouraged to
review my code and make it better.

** Installation

Since this package is not yet ready for public use, there's no better
way but ~load~.

** Usage

Do ~M-x acm-mode~ in the buffer of the source file when needed.  A
special window configuration will be created, where your source file
is placed on the left, and the input and the output buffers are placed
on the right.

If your source file name is ~FILE.cpp~, then ~acm-mode~ will look for
~FILE.in~, and automatically fill in the input buffer with the
contents of that file.  But the input buffer is still not associated
with that file.

Commands provided by ~acm.el~ also work in the input and the output
buffers, but they do NOT work outside these three buffers.

*** Jumping among buffers

+ ~acm-source~ :: Jump to the source buffer.
+ ~acm-input~ :: Jump to the input buffer.
+ ~acm-output~ :: Jump to the output buffer.

*** Compile and test

+ ~acm-compile~ :: Compile the source file, using sane default
                   ~-std=c++14 -ggdb~, generating an execuatble named
                   ~FILE~ (given your source file is named
                   ~FILE.cpp~).
+ ~acm-run~ :: Run the previously built executable.

*** Window configuration

+ ~acm-restore-window-configuration~ :: Restore the default window configuration.

*** Key bindings

The default key bindings are kept as intuitive as possible.

| Keys    | Commands                           |
|---------+------------------------------------|
| ~C-c s~ | ~acm-source~                       |
| ~C-c i~ | ~acm-input~                        |
| ~C-c o~ | ~acm-output~                       |
| ~C-c c~ | ~acm-compile~                      |
| ~C-c r~ | ~acm-run~                          |
| ~C-c w~ | ~acm-restore-window-configuration~ |
